before_script:
  - sudo sed -i "s/use-ipv6=yes/use-ipv6=no/" /etc/avahi/avahi-daemon.conf
  - sudo mkdir /var/lib/4store/
  - sudo chown $USER:$USER /var/lib/4store/
  - sudo add-apt-repository ppa:yves-raimond/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y 4store

script: "./run.sh"
